{% set name = "anaconda-cli-base" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 1d9355e6e9c4b9221ef9ded81fe9415115c8b4a26de73ee158f443ec1dbe7a06
  patches:
    - 0001-windows-path-fix.patch  # [win]

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - anaconda = anaconda_cli_base.cli:app

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
  run:
    - python
    - click <8.2
    - pydantic-settings >=2.3
    - readchar
    - rich
    - typer
    - tomli
    - packaging >=23.0
  run_constrained:
    # Ensure that a version of anaconda-cli-base cannot be installed if an incompatible
    # older version of anaconda-client is installed.
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0

test:
  source_files:
    - tests
  imports:
    - anaconda_cli_base
  requires:
    - pip
    - pytest
    - pytest-mock
    - types-requests
  commands:
    - pip check
    - anaconda -h
    - anaconda -V
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  dev_url: https://pypi.org/project/anaconda-cli-base
  doc_url: https://pypi.org/project/anaconda-cli-base

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
