{% set name = "anaconda-cli-base" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda_cli_base-{{ version }}.tar.gz
  sha256: da0a8278ba4b9766e0df01fc8b15e8c2d1030c7229c51adddf3f0e84430601f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - anaconda = anaconda_cli_base.cli:app

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - click <8.2
    - readchar
    - rich
    - typer
    - pydantic-settings >=2.3
    - tomli
    - packaging >=23.0
  run_constrained:
    # Ensure that a version of anaconda-cli-base cannot be installed if an incompatible
    # older version of anaconda-client is installed.
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - anaconda_cli_base
  commands:
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""
    - pip check

about:
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  home: https://github.com/anaconda/anaconda-cli-base
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
